package com.example.foodorderingsystem.PresentationLayer;

import com.example.foodorderingsystem.BusinessLayer.Admin;
import com.example.foodorderingsystem.DataAccessLayer.AdminDataAccess;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class AdminRegisterController {
    @FXML private TextField firstNameField;
    @FXML private TextField middleNameField;
    @FXML private TextField lastNameField;
    @FXML private TextField emailField;
    @FXML private PasswordField passwordField;
    @FXML private PasswordField confirmPasswordField;
    @FXML private TextField phoneField;
    @FXML private TextField salaryField;
    @FXML private ComboBox<String> restaurantComboBox;
    @FXML private ListView<String> restaurantListView;
    @FXML private Label errorMessage;

    private AdminDataAccess adminDataAccess;
    private ObservableList<String> selectedRestaurants = FXCollections.observableArrayList();
    private ObservableList<Integer> selectedRestaurantIds = FXCollections.observableArrayList();

    public void initialize() {
        adminDataAccess = new AdminDataAccess();
        restaurantListView.setItems(selectedRestaurants);

        // Load restaurants for the ComboBox
        // Note: This is a placeholder - you'd need to implement a method to get restaurants
        loadRestaurantsForComboBox();

    }

    private void loadRestaurantsForComboBox() {
        // This would be implemented to load restaurants from database
        // For now, just a placeholder with sample data
        List<String> restaurants = Arrays.asList("Restaurant 1", "Restaurant 2", "Restaurant 3");
        restaurantComboBox.setItems(FXCollections.observableArrayList(restaurants));
    }

    @FXML
    protected void handleAddRestaurant() {
        String selectedRestaurant = restaurantComboBox.getValue();
        if (selectedRestaurant != null && !selectedRestaurant.isEmpty()) {
            if (!selectedRestaurants.contains(selectedRestaurant)) {
                selectedRestaurants.add(selectedRestaurant);
                // In a real application, you'd get the actual restaurant ID
                selectedRestaurantIds.add(selectedRestaurants.indexOf(selectedRestaurant) + 1);
            }
        }
    }

    @FXML
    protected void handleRegister(ActionEvent event) {
        // Clear any previous error messages
        errorMessage.setVisible(false);

        // Validate form inputs
        if (!validateInputs()) {
            return;
        }

        try {
            // Get form data
            String firstName = firstNameField.getText().trim();
            String middleName = middleNameField.getText().trim();
            String lastName = lastNameField.getText().trim();
            String email = emailField.getText().trim();
            String password = passwordField.getText().trim();
            String phone = phoneField.getText().trim();

            // Parse salary (add error handling for invalid input)
            double salary = 0.0;
            try {
                salary = Double.parseDouble(salaryField.getText().trim());
            } catch (NumberFormatException e) {
                showError("Salary must be a valid number.");
                return;
            }

            // Create admin object
            Admin newAdmin = new Admin(
                    email,
                    password,
                    firstName,
                    middleName,
                    lastName,
                    0, // adminId will be generated by database
                    salary,
                    Arrays.asList(phone)
            );

            // Set the restaurants managed by this admin
            if (!selectedRestaurantIds.isEmpty()) {
                List<Integer> restaurantIds = new ArrayList<>(selectedRestaurantIds);
                newAdmin.setRestaurantsManaged(restaurantIds);
            }

            // Register the admin in the database
            adminDataAccess.insertAdmin(newAdmin);

            // Show success message and navigate to login
            Alert alert = new Alert(Alert.AlertType.INFORMATION);
            alert.setTitle("Registration Successful");
            alert.setHeaderText("Admin Account Created");
            alert.setContentText("Admin account has been created successfully. Please login with your credentials.");
            alert.showAndWait();

            // Navigate to login screen
            handleLoginLink(event);

        } catch (SQLException e) {
            showError("Database error: " + e.getMessage());
        } catch (Exception e) {
            showError("An error occurred: " + e.getMessage());
        }
    }

    private boolean validateInputs() {
        // Validate required fields
        if (firstNameField.getText().trim().isEmpty() ||
                lastNameField.getText().trim().isEmpty() ||
                emailField.getText().trim().isEmpty() ||
                phoneField.getText().trim().isEmpty() ||
                passwordField.getText().isEmpty() ||
                confirmPasswordField.getText().isEmpty() ||
                salaryField.getText().trim().isEmpty()) {

            showError("Please fill in all required fields.");
            return false;
        }

        // Validate email format
        if (!emailField.getText().trim().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            showError("Please enter a valid email address.");
            return false;
        }

        // Validate password match
        if (!passwordField.getText().equals(confirmPasswordField.getText())) {
            showError("Passwords do not match.");
            return false;
        }

        // Validate salary is a positive number
        try {
            double salary = Double.parseDouble(salaryField.getText().trim());
            if (salary <= 0) {
                showError("Salary must be a positive number.");
                return false;
            }
        } catch (NumberFormatException e) {
            showError("Please enter a valid salary amount.");
            return false;
        }

        return true;
    }

    @FXML
    protected void handleLoginLink(ActionEvent event) {
        try {
            Parent loginView = FXMLLoader.load(getClass().getResource("/com/example/foodorderingsystem/login-view.fxml"));
            Scene loginScene = new Scene(loginView);
            Stage window = (Stage) ((Node) event.getSource()).getScene().getWindow();
            window.setScene(loginScene);
            window.show();
        } catch (IOException e) {
            showError("Error navigating to login: " + e.getMessage());
        }
    }

    private void showError(String message) {
        errorMessage.setText(message);
        errorMessage.setVisible(true);
    }
}